name: Infrastructure CI/CD Pipeline

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "1220-IAC"
  CONFIG_DIRECTORY: "./"
  
jobs:
  Deploy_Resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure Terraform Cloud API Token
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials": {"app.terraform.io": {"token": "${{ secrets.TFE_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="LANDING_BUCKET=${{ secrets.LANDING_BUCKET }}" -var="LOGGING_BUCKET_NAME=${{ secrets.LOGGING_BUCKET_NAME }}" -var="FUN_BUCKET_KEY=${{ secrets.FUN_BUCKET_KEY }}" -var="LOGGING_BUCKET_KEY=${{ secrets.LOGGING_BUCKET_KEY }}" -var="TITLE_BUCKET_KEY=${{ secrets.TITLE_BUCKET_KEY }}" 
        working-directory: terraform
